### ISSUE TITLE
Issue when starting salt-master and minion after switching to RAET

### ISSUE THREAD

**Issue by ahodges22** [saltstack/raet#67]
I've got all the dependencies installed added RAET transport to the master and minion configs. When I try to restart both the salt-minion and master, it crashes and I get this stack trace:

Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 59, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 71, in factory
    return RAETCaller(opts, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 282, in __init__
    self.stack = self._setup_caller_stack(opts)
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 352, in _setup_caller_stack
    stackname = 'caller' + nacling.uuid(size=18)
  File "/usr/lib/python2.6/site-packages/raet/nacling.py", line 576, in uuid
    return ((front + back)[:size]).decode(encoding='ISO-8859-1')
TypeError: decode() takes no keyword arguments

Any ideas? I feel like Python 2.6 over 2.7 might be a part of this issue.

**Comment by SmithSamuelM** [comment]
Thats what it looks like for the string .decode method.

Changed in version 2.7: Support for keyword arguments added.
Fix is to remove the keyword argument

**Comment by ahodges22** [comment]
Removed that argument, and master now stays running, but now the minions keep crashing with this stack trace:

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 298, in minion_run
    minion = salt.Minion()  # daemonizes here
AttributeError: 'module' object has no attribute 'Minion'

**Comment by ahodges22** [comment]
Anyone have any insight?

**Comment by lvii** [comment]
Hi, 

It seemed that `python-raet-0.6.3-2.el6.noarch` still has this problem under **CentOS 6**.

I have install the last **salt 2016.3.4** with RAET enabled.

```
# rpm -qa|grep raet
python-raet-0.6.3-2.el6.noarch

# rpm -qa|grep salt
salt-2016.3.4-1.el6.noarch
salt-repo-latest-1.el6.noarch
salt-master-2016.3.4-1.el6.noarch
```

`salt-master` service failed started with the same error log :

in this issue it show it has been fix ?

https://github.com/saltstack/salt/issues/25858

```
2016-11-24 19:16:22,781 [salt.log.setup   ][ERROR   ][22167] An un-handled exception was caught by salt's global exception handler:
TypeError: decode() takes no keyword arguments
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 90, in salt_master
    master.start()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 207, in start
    self.master.start()
  File "/usr/lib/python2.6/site-packages/salt/daemons/flo/__init__.py", line 100, in start
    consolepath=consolepath,
  File "/usr/lib/python2.6/site-packages/ioflo/app/run.py", line 137, in run
    skedder.run()
  File "/usr/lib/python2.6/site-packages/ioflo/base/skedding.py", line 273, in run
    status = tasker.runner.send(tasker.desire)
  File "/usr/lib/python2.6/site-packages/ioflo/base/framing.py", line 630, in makeRunner
    self.enterAll() #activates, resets .done state also .desire may change here
  File "/usr/lib/python2.6/site-packages/ioflo/base/framing.py", line 411, in enterAll
    self.enter(self.actives)
  File "/usr/lib/python2.6/site-packages/ioflo/base/framing.py", line 423, in enter
    frame.enter()
  File "/usr/lib/python2.6/site-packages/ioflo/base/framing.py", line 1244, in enter
    act() #call entryAction
  File "/usr/lib/python2.6/site-packages/ioflo/base/acting.py", line 99, in __call__
    return (self.actor(**self.parms))
  File "/usr/lib/python2.6/site-packages/ioflo/base/acting.py", line 524, in __call__
    return self.action(**kwa)
  File "/usr/lib/python2.6/site-packages/salt/daemons/flo/core.py", line 292, in action
    stackname=name)
  File "/usr/lib/python2.6/site-packages/salt/daemons/salting.py", line 62, in __init__
    self.saltRaetKey = RaetKey(opts)
  File "/usr/lib/python2.6/site-packages/salt/key.py", line 1034, in __init__
    Key.__init__(self, opts)
  File "/usr/lib/python2.6/site-packages/salt/key.py", line 548, in __init__
    listen=False)
  File "/usr/lib/python2.6/site-packages/salt/utils/event.py", line 135, in get_event
    opts=opts)
  File "/usr/lib/python2.6/site-packages/salt/utils/raetevent.py", line 50, in __init__
    self.__prep_stack(listen)
  File "/usr/lib/python2.6/site-packages/salt/utils/raetevent.py", line 60, in __prep_stack
    self.stack = transport.jobber_stack = self._setup_stack(ryn=self.ryn)
  File "/usr/lib/python2.6/site-packages/salt/utils/raetevent.py", line 98, in _setup_stack
    name = 'event' + nacling.uuid(size=18)
  File "/usr/lib/python2.6/site-packages/raet/nacling.py", line 576, in uuid
    return ((front + back)[:size]).decode(encoding='ISO-8859-1')
TypeError: decode() takes no keyword arguments
```

This is my `salt --versions-report` output :

```
# salt --versions-report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.3.8
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: 0.6.3
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-642.6.1.el6.x86_64
         system: Linux
        version: CentOS 6.6 Final
```

**Comment by lvii** [comment]
CentOS 6.x  python-raet rpm need to update
